user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;


    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    server {
        listen 80;

        root /usr/share/nginx/src;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /dist/ {
            alias /usr/share/nginx/src/dist/;
            try_files $uri $uri/ /dist/index.html;
        }

        location /_expo/ {
            alias /usr/share/nginx/src/dist/_expo/;
        }

        location /assets/ {
            try_files $uri /dist$uri =404;
        }

        location = /favicon.ico {
            alias /usr/share/nginx/src/dist/favicon.ico;
        }

        location = /icon.png {
            alias /usr/share/nginx/src/icon.png;
        }

        location /chat/ws/ {
            proxy_pass http://server:5000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_read_timeout 3600;
            proxy_send_timeout 3600;
        }

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://server:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_read_timeout 300;
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
        }
        client_max_body_size 20M;
    }
}